site:
  title: repSwim Documentation
  start_page: repswim::index.adoc
content:
  sources:
    - url: .
      start_path: src/docs
      branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./build/docs/site
